### PR TITLE
Initial setup for i18n

### PR DESCRIPTION
**Pull request by aleesaan**
## What changes have been made? 
Added initial support for internationalization. I kept it simple not to increase the scope of the case, but these are the things need to follow up (in order):

1. Add the translation function (`$t()`) in every (user-facing) string in the app;
2. Setup a way to extract the translations (perhaps using [this package](https://www.npmjs.com/package/vue-i18n-extract-translations)?) on commits to master - the specifics are to be discussed;
3. Setup a way to push the translation files to a translation service (we're currently thinking of [Loco](https://localise.biz/)), as well as accounts for translators so to translate those files;
4. Setup a way to pull the (translated) translation files, possibly when building / deploying the app.

I will attach before/after screenshots once we finalize the design and fix the current issue with styles.

### Issues resolved by these changes
#39

### CODE REVIEW

**Comment by aleesaan** [comment]
I just added some changes to complete the point 1 from above, and I also added the package mentioned in point 2 to extract them.

I still need to do two things in this case:
- Figure out how to properly handle missing translations, as currently strings with interpolations (e.g. `Published on {date}`) don't work;
- Figure out how to lazy load translations, as we shouldn't import the translation files in the main app bundle. I found [this guide](https://kazupon.github.io/vue-i18n/guide/lazy-loading.html) but couldn't get it to work, will need to look into it more.

**Comment by kajdehoop** [comment]
@aleesaan Awesome, looks good! Thank you :D 

The issue also has point 3 & 4 about using a translation service like Loco to manage translations. Maybe we should merge this request first and then put point 3 & 4 into a new issue? @SamLubbers

**Review by kajdehoop — APPROVED** [review]

**Comment by kajdehoop** [comment]
@SamLubbers I can't merge this PR as I don't have write access, can you do that? ;) Ale will create a new separate issue for the managing of the translations

**Comment by SamLubbers** [comment]
Hey @kajdehoop good to see that you two have got the translations working!! I think that you do have write access since you're in the XRNL team for the volunteer platform. I think what is needed to merge this PR is for you to accept the changes (go to `file changed > review changes > approve > submit review`). If this doesn't work I'll see what I can change to give you write access :ok_hand:

**Pull request merged**
