### PR TITLE
XR logo spinner

### PR DESCRIPTION
**Pull request by reinvdwoerd**
## What changes have been made? 

I replaced the spinner with an XR spinner.
Screen Shot 2020-08-14 at 20 28 15

Screen Shot 2020-08-14 at 20 28 15

## Rationale for these changes

It adds some fun and character, and the logo is a perfect fit for a spinner.

### CODE REVIEW

**Comment by reinvdwoerd** [comment]
@SamLubbers Very good points, I'll act on them today!

**Comment by reinvdwoerd** [comment]
Alright, the color has been changed

Screenshot 2020-08-16 at 19 16 18

**Comment by reinvdwoerd** [comment]
Hmmm, changing the tests is a bit harder than I thought, because the Lottie animation needs to respond to the theme's primary color...

**Comment by SamLubbers** [comment]
We don't need to test that a theme colour is used for this animation. We can just test that the animation is rendered. Let's resolve this when we have finished other more urgent issues.

**Comment by SamLubbers** [comment]
Closing PR as it's been active for too long and not merged yet. I made a new issue for it in case someone wants to implement it in the future #137

**Pull request closed without merging**
